list: $/hardiksatasiya/branchmanagement/models/advertisement/columns.yaml
modelClass: HardikSatasiya\BranchManagement\Models\Advertisement
title: Advertisement
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hardiksatasiya/branchmanagement/advertisement/update/:id'
